--INSERT INTO person(id, last_name,first_name, date_of_birth, email, phone_number) VALUES (1,'Doe', 'John', '1982/04/17', 'john.doe@foobar.com', '+5901233');
--INSERT INTO person(id, last_name,first_name, date_of_birth, email, phone_number) VALUES(2, 'Ann', 'Mary', '1960/02/29', 'mary.ann@foobar.com', '+594322');
--INSERT INTO person(id,last_name,first_name, date_of_birth, email, phone_number) VALUES(3, 'Tire', 'Mike', '1986/04/19', 'mike.tire@foobar.com', '+532344');
